server:
  port: 8080

spring:
  application:
    name: banco
  datasource:
    url: jdbc:h2:mem:mydb
    username: banco
    password: 123
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-ui